version: '3.8'

services:
  postgres:
    container_name: "postgres_db"
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - postgres_network


networks:
  postgres_network:
    driver: bridge

volumes:
    postgres_volume:
