version: '3.8'

services:
  postgres:
    container_name: "postgres_db"
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - postgres_network

  redis:
    container_name: "redis"
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_volume:/root/redis
      - redis_volume:/usr/local/etc/redis/redis.conf

networks:
  postgres_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
    postgres_volume:
    redis_volume:
      driver: local
