version: '3.7'

services:
  postgres:
    container_name: postgres_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - "${DB_PORT}:5432"

  redis:
    container_name: redis
    image: redis:7
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}

  fastapi-template-app:
    container_name: fastapi_app
    env_file:
      - .env
    build:
      context: .
    command: ["/api/deployment/docker-entrypoint.sh"]
    ports:
      - 9999:8000
    depends_on:
      - postgres
      - redis

  celery:
    container_name: celery_app
    env_file:
      - .env
    build:
      context: .
    command: ["/api/deployment/celery-entrypoint.sh", "celery"]
    depends_on:
      - redis

  flower:
    container_name: flower_app
    env_file:
      - .env
    build:
      context: .
    command: ["/api/deployment/celery-entrypoint.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
